Get all monthly info
dadosjusbr/storage pull request #103
Opened 2023-02-08 11:09 UTC by duardoqueiroz

Pr que cria um novo método que pega as coletas de todos os anos de um órgão. Jessé me pediu para que esse método fosse criado.  Após a entrada da pr, irei adicionar uma nova rota na api que acessa esses dados

2023-02-08 17:44 UTC, danielfireman requested changes

2023-02-08 17:44 UTC, danielfireman commented on repo/database/postgres.go
> +	var results = make(map[string][]models.AgencyMonthlyInfo)
Me parece bastante informação para enviar para o FE. Precisamos mesmo dos dados detalhados de todos os meses de todos os anos? Não podemos agregar os dados por ano? Como isso é uma coisa que vai ser usada pela UI, penso que a API pode ser mais específica aqui. 

Poderia confirmar, por favor?

2023-02-09 15:51 UTC, duardoqueiroz commented on repo/database/postgres.go
> +	var results = make(map[string][]models.AgencyMonthlyInfo)
Conversei com o Jessé e realmente o que ele estava querendo era um resumo dos dados anuais de um órgão. Modificação feita!

2023-02-09 19:00 UTC, danielfireman requested changes

2023-02-09 19:00 UTC, danielfireman commented on repo/database/dto/annualMonthlyInfo.go
> +type AnnualMonthlyInfoDTO struct {
`AnnualSummary` .. Por favor, atualizar em todos os lugares abaixo.

Pedindo isso pois o termo `MonthlyInfo` vem sendo usado de uma forma bem precisa no storage. Ele é uma estrutura de dados. Reutilizar o termo vai confundir muito mais que esclarcer.

2023-02-12 04:36 UTC, merged