Retornando resumo_rubricas para api
dadosjusbr/storage pull request #125
Opened 2023-12-13 19:35 UTC by joellensilva

- Algumas rotas precisam de modificação no storage para retornar esses campos (ex.: a rota que faz o gráfico da página principal)
- Adicionando o campo aos testes

2023-12-13 19:53 UTC, danielfireman commented on repo/database/dto/annuaISummary.go
> +	ItemSummary
Não seria `ItemSummary ItemSummary`? Nesse caso pode ter funcionado, mas você está usando embedded types e não tenho certeza se é o que você queria.

2023-12-13 19:53 UTC, danielfireman commented on repo/database/dto/generalMonthlyInfo.go
> +	ItemSummary
Mesmo comentário que fiz acima sobre estar usando embedded types.

2024-01-09 13:24 UTC, joellensilva commented on repo/database/dto/annuaISummary.go
> +	ItemSummary
Após esse comentário, o código foi [modificado](https://github.com/dadosjusbr/storage/blob/eac98bee8164e2c76adcfedac1001dd1de768c4b/repo/database/dto/annuaISummary.go#L16) seguindo a [documentação](https://gorm.io/docs/models.html#Embedded-Struct) da biblioteca utilizada.

```
ItemSummary        ItemSummary `gorm:"embedded"
````

2024-01-09 13:55 UTC, danielfireman requested changes

2024-01-09 13:55 UTC, danielfireman commented on models/monthlyInfo.go
> +	ItemSummary        ItemSummary `json:"resumo_rubricas,omitempty"`
Poderia verificar esse ponto, por favor?

2024-01-09 13:55 UTC, danielfireman commented on models/monthlyInfo.go
> +	ItemSummary        ItemSummary `json:"resumo_rubricas,omitempty"`
Lembrando que ele aparece acima também.

2024-01-09 14:49 UTC, joellensilva commented on repo/database/dto/annuaISummary.go
> +	ItemSummary        ItemSummary `gorm:"embedded"`
Sim, era a minha intenção. Diferentemente dos outros campos, esse, ItemSummary, recebe uma estrutura de dados, semelhante a essa aplicação [aqui](https://github.com/dadosjusbr/storage/blob/master/repo/database/dto/monthlyInfoDTO.go#L32#L33)

A ideia é, que em vez de acessarmos diretamente os valores, como nos demais campos, os valores estejam organizados no seu próprio grupo/campo.

Sobre usar a versão do Go ou do Gorm, apesar da finalidade ser a mesma, acredito que a versão do Gorm é mais legível, sendo possível evidenciar a field, seu tipo e que é um embedded type. A expressão `ItemSummary ItemSummary`, como sugerido, não é possível, devido a conflitos com a biblioteca, o que resulta em erros. Daí a necessidade de utilizar embedded type.

2024-01-09 19:49 UTC, danielfireman approved these changes

2024-01-09 19:49 UTC, merged