faet: implement agreggations collection
dadosjusbr/storage pull request #39
Opened 2021-08-17 21:18 UTC by Manuel-Antunes

Esse PR
* cria um struct para as agreggations
* inclui a collection de agreggations no construtor do db
* cria uma função para adicionar novas agregações ao sistema
* cria uma função para obter agregações do sistema

2021-08-18 01:11 UTC, danielfireman requested changes

2021-08-18 01:11 UTC, danielfireman commented on client.go
> +		return fmt.Errorf("error while creating a new agreggation %q", err)
```suggestion
		return fmt.Errorf("error while storing a new agreggation %q", err)
```

2021-08-18 01:11 UTC, danielfireman commented on mgo.go
> -func NewDBClient(url, dbName, monthlyInfoCol, agencyCol string) (*DBClient, error) {
Isso vai quebrar a API. Você vai precisar, inclusive, adicionar uma nova variável de ambiente no heroku.

2021-08-18 01:11 UTC, danielfireman commented on mgo.go
> +	aid *string,
Coloque para receber uma `Aggregation`. A utilização dessa API vai ficar bem mais limpa.

2021-08-18 01:16 UTC, Manuel-Antunes commented on mgo.go
> -func NewDBClient(url, dbName, monthlyInfoCol, agencyCol string) (*DBClient, error) {
Eu tlg, mas a ideia era realmente já botar na API e corrigir tudo

2021-08-18 01:17 UTC, Manuel-Antunes commented on mgo.go
> +	aid *string,
Ok, aí no caso, no package n passa nada ? mas tipo, as pessoas que vão trabalhar no código, como elas vão saber que não precisam passar um package pra rodar ?

2021-08-18 10:51 UTC, danielfireman commented on mgo.go
> +	aid *string,
Não entendi a pergunta. Poderia reformular, por favor?

Meu comentário é que, a utilização dos 4 parâmetros levaria a chamadas assim:

```go
GetAggregation("mppb", nil, nil, nil)
```

Daí eu sugeri:

```go
GetPackage(Package{AID:"mppb"})
```

Sim, aproveitando para também sugerir que a gente mude tudo de Aggregation para Package, afinal de contas, é isso que vamos trabalhar 😄

2021-08-18 10:52 UTC, danielfireman commented on mgo.go
> -func NewDBClient(url, dbName, monthlyInfoCol, agencyCol string) (*DBClient, error) {
Bacana!

2021-08-18 11:37 UTC, danielfireman reviewed
Vamos tornar a mudança mais específica. `Package` passa uma mensagem mais direta sobre o que iremos armazenar (tem mais a ver com o storage).

2021-08-18 11:37 UTC, danielfireman commented on agregation.go
> +type Agreggation struct {
Por favor, renomear para `Package`

2021-08-18 11:37 UTC, danielfireman commented on client.go
> +// Store stores an agreggation in the database.
```suggestion
// Store stores a package in the database.
```

2021-08-18 11:37 UTC, danielfireman commented on client.go
> +func (c *Client) StoreAgreggation(agreggation Agreggation) error {
Renomear parâmetro para `package`

```suggestion
func (c *Client) StorePackage(agreggation Agreggation) error {
```

2021-08-18 11:37 UTC, danielfireman commented on mgo.go
> +	aggregationCol string
```suggestion
	packageCol string
```

2021-08-18 11:37 UTC, danielfireman commented on mgo.go
> +func NewDBClient(url, dbName, monthlyInfoCol, agencyCol string, aggregationCol string) (*DBClient, error) {
Renomear parâmetro para `packageCol`

2021-08-18 20:21 UTC, Manuel-Antunes commented on client.go
> +func (c *Client) StoreAgreggation(agreggation Agreggation) error {
O parâmetro não pode ser renomeado para package pois é uma palavra reservada do golang

2021-08-19 13:51 UTC, danielfireman approved these changes
Bacana!

Por favor endereçar os dois comentários que fiz abaixo antes de fazer merge.

2021-08-19 13:51 UTC, danielfireman commented on client.go
> +func (c *Client) StoreAgreggation(newPackage Package) error {
```suggestion
func (c *Client) StorePackage(newPackage Package) error {
```

2021-08-19 13:51 UTC, danielfireman commented on mgo.go
> +func (c *DBClient) GetAgreggation(pkgOpts PackageFilterOpts) (*Package, error) {
```suggestion
func (c *DBClient) GetPackage(pkgOpts PackageFilterOpts) (*Package, error) {
```

2021-08-19 20:21 UTC, merged