S3 store
dadosjusbr/storage pull request #56
Opened 2022-11-02 22:19 UTC by duardoqueiroz

Criei uma interface para o armazenador de arquivos e fiz a implementação do armazenamento no s3.

2022-11-04 17:43 UTC, danielfireman requested changes
O movimento é muito bom, mas fiquei com uma dúvida abaixo.

2022-11-04 17:43 UTC, danielfireman commented on aws.go
> +	for _, file := range Files {
Não iríamos comprimir os backups e fazer upload apenas do zip?

2022-11-04 17:43 UTC, danielfireman commented on client.go
> +func (c *Client) Close(db *DBClient, cloud IStorageService) error {
Precisamos passar esse e o Istorage como referência?

2022-11-07 10:38 UTC, duardoqueiroz commented on aws.go
> +	for _, file := range Files {
Exatamente. Na real, parando pra pensar, nós nem vamos precisar desse método Backup. Podemos utilizar o método UploadFile para realizar o upload do backup.

2022-11-07 10:39 UTC, duardoqueiroz commented on aws.go
> +	for _, file := range Files {
Acabei de remover o método

2022-11-07 11:38 UTC, danielfireman commented on aws.go
> +	for _, file := range Files {
Exatamente!

2022-11-07 11:42 UTC, danielfireman approved these changes

2022-11-07 11:43 UTC, merged