Test getOPE
dadosjusbr/storage pull request #82
Opened 2023-01-19 02:39 UTC by duardoqueiroz

Primeira implementação dos testes no storage. Essa implementação foi uma ideia inicial, aceito melhorias para deixar o código mais limpo e também mais casos de testes importantes.

Coisas feitas:
- Criei um docker compose para subir um banco de testes local
- Criei mocks, utilizando o [mockgen](https://github.com/golang/mock) , a partir das interfaces do banco de dados e do file storage.
- Criei o teste do método getOPE do arquivo client.go. Os casos de testes feitos foram:
  - teste quando forem os órgãos retornados corretamente do PostgresDb. 
  - teste quando um erro for retornado do PostgresDb.
  - teste quando o PostgresDb retornar um array vazio(órgãos não existirem).
- Criei o teste do método getOPE do arquivo postgres.go. Os casos de testes feitos foram:
  - teste quando os órgãos daquela UF existirem.
  - teste quando os órgãos daquela UF não existirem.
  - teste quando a UF vier em letra minúscula(diferente de como salvamos no banco.)

2023-01-21 12:25 UTC, danielfireman requested changes

2023-01-21 12:25 UTC, danielfireman commented on .github/workflows/tests.yaml
> +      - uses: actions/setup-go@v3
Dado que você especificou a o contêiner na linha 6, essa diretiva é necessária?

2023-01-21 12:25 UTC, danielfireman commented on README.md
> +mockgen --source ./repo/database/idatabase_repository.go --destination ./repo/database/database_mock.go
```suggestion
mockgen --source ./repo/database/interface.go --destination ./repo/database/database_mock.go
```

2023-01-21 12:25 UTC, danielfireman commented on README.md
> +mockgen --source ./repo/file_storage/istorage_repository.go --destination ./repo/file_storage/file_storage_mock.go
```suggestion
mockgen --source ./repo/file_storage/interface.go --destination ./repo/file_storage/file_storage_mock.go
```

2023-01-21 12:25 UTC, danielfireman commented on README.md
> +Para conseguir testar as funcionalidades que acessam diretamente o banco de dados, em /repo/database/postgres_test.go, é necessário ter o banco de dados rodando. Os passos são:
```suggestion
Para conseguir testar as funcionalidades que acessam diretamente o banco de dados, em `repo/database/postgres_test.go`, é necessário ter o banco de dados rodando. Os passos são:
```

2023-01-21 12:25 UTC, danielfireman commented on README.md
> +- Renomeie o arquivo .env.example para .env
Por não chamar logo de `.env.test`?

2023-01-21 12:25 UTC, danielfireman commented on repositories/database/postgres/.env.example
> +POSTGRES_TEST_URL="host=localhost port=5432 user=dadosjusbr_test dbname=dadosjusbr_test password=dadosjusbr_test sslmode=disable"
Isso não me parece uma URL.

2023-01-21 12:25 UTC, danielfireman commented on docker-compose.yml
> +version: "3"
Esse arquivo é apenas usado para teste da camada mais interna, certo? Por que ele não no diretório postgres?

2023-01-21 12:25 UTC, danielfireman commented on init_db.sql
> +\connect dadosjusbr_test
Mover para o diretório postgres

2023-01-21 12:25 UTC, danielfireman commented on docker-compose.yml
> +version: "3"
Na realidade, dado que você tem apenas um serviço, você não precisa do arquivo `docker-compose.yml`. Pode fazer tudo isso no `Dockerfile`.

2023-01-21 12:25 UTC, danielfireman commented on Dockerfile
> +
Como esse cara é apenas usado para testes, minha sugestão é mover ele para o diretório `postgres`

2023-01-21 12:25 UTC, danielfireman commented on repo/database/postgres_test.go
> +	godotenv.Load("../../.env")
Não acho que precisamos de um ENV file para apenas uma variável de ambiente. Pode colocar essas variáveis hardcoded aqui e um comentário que elas devem seguir o padrão que está no Dockerfile. 

A vantagem disso é que precisamos olhar para menos arquivos para entender o teste. Que já é bastante complexo.

2023-01-21 12:25 UTC, danielfireman commented on repositories/database/postgres/.env.example
> +POSTGRES_TEST_URL="host=localhost port=5432 user=dadosjusbr_test dbname=dadosjusbr_test password=dadosjusbr_test sslmode=disable"
Dado meu comentário no arquivo de teste, esse arquivo pode ser removido

2023-01-21 12:25 UTC, danielfireman commented on repo/database/postgres_test.go
> +
Ao invés de usar esse modelo de ter uma classe e declarar os métodos na mão, minha sugestão é usar o método `TestMain` para realizar a configuração da conexão com o BD:

http://cs-guy.com/blog/2015/01/test-main/

```go
func TestMain(m *testing.M) {
      if err := getDbTestConnection(); err != nil {
		t.Fatal(err)
    }
    code := m.Run() 
    // encerrar conexão com o BD
    os.Exit(code)
}
```

Isso vai te permitir usar métodos normais de teste. Creio que vai tornar o teste mais claro

2023-01-22 19:48 UTC, danielfireman commented on README.md
> +- Renomeie o arquivo .env.example para .env
Na realidade, não precisaremos desse `.env`

2023-01-24 00:36 UTC, duardoqueiroz commented
Optei por utilizar a variavel de ambiente para se conectar ao banco, pois a url de conexao local difere da url de conexao necessária no workflow. 

Nos steps do workflow de teste, tive que executar vários comandos para que o script repo/database/init_db.sql fosse executado para que as tabelas fossem criadas. Essa foi a única forma que eu encontrei de criar as tabelas sem adicionar um script a mais só pra cria-las. Tive que instalar o docker em um dos steps pelo fato de o step não ter acesso a ele nativamente. Logo após, o que eu faço é um trabalho de copiar o arquivo repo/database/init_db.sql para o container e depois executar os comandos dele utilizando o psql. Tentei subir o banco várias vezes e essa foi a única forma que realmente funcionou.

2023-01-24 13:07 UTC, danielfireman approved these changes
Massa!!!

2023-01-24 13:07 UTC, merged